### ISSUE TITLE
"Camera calibration file XXX not found" is misleading.

### ISSUE THREAD

**Issue by liborw** [ros-perception/image_common#14] opened 2013-05-29 12:37 UTC
The `Camera calibration file XXX not found` error message is shown even if the file is found, but not parsed.

**Comment by jack-oquin** [comment] 2013-05-29 13:52
Thanks for the report.

I am closing this as a duplicate of #12, which I am currently working on for release in Hydro. Please make sure that issue describes your requirements. Also, I would like to know if you prefer any specific error messages to be **Info** or **Warning**. 

Perhaps you can help with testing, once a fix is committed.

If you believe this is _not_ a duplicate of #12, please let me know so I can re-open this issue.

**Closed as completed by jack-oquin** 2013-05-29 13:52 UTC
Labels: duplicate

**Comment by liborw** [comment] 2013-05-30 08:35
When the file is really missing it could be just warning, but when the file is there and the parsing fails it could be an error message reporting that parsing failed. We are stuck on fuerte.

I found that there is error reporting in [parse_yml.cpp#L192](https://github.com/ros-perception/image_common/blob/groovy-devel/camera_calibration_parsers/src/parse_yml.cpp#L192) but it doest show in the console.

**Comment by jack-oquin** [comment] 2013-05-30 14:40
It looks like your problem _is_ a duplicate of #12. Please make further comments there.

I do not plan to release a fix for Fuerte. It was released long ago and is now stable. There is no telling who might depend on or at least expect the current behavior.

**Comment by nirmalauwucst** [comment] 2016-06-01 04:35
in ROS indigo also,
[ WARN] [1464753652.256748258]: Camera calibration file /home/ubuntu/.ros/camera_info/rgb_0.yaml not found.
[ WARN] [1464753652.256849676]: Using default parameters for RGB camera calibration.
[ WARN] [1464753652.256945094]: Camera calibration file /home/ubuntu/.ros/camera_info/depth_0.yaml not found.
[ WARN] [1464753652.256998845]: Using default parameters for IR camera calibration.

and it will not launch openni

**Comment by jack-oquin** [comment] 2016-06-01 14:09
Those are warnings, not fatal errors. If those files really do not exist, that is not a problem.

There must be some other reason why openni did not launch.

**Comment by kanishkanarch** [comment] 2020-07-01 12:34
> When the file is really missing it could be just warning, but when the file is there and the parsing fails it could be an error message reporting that parsing failed. We are stuck on fuerte.
> 
> I found that there is error reporting in [parse_yml.cpp#L192](https://github.com/ros-perception/image_common/blob/groovy-devel/camera_calibration_parsers/src/parse_yml.cpp#L192) but it doest show in the console.

I've the file missing with the folder in which the file should be. My error says "Camera calibration file /home/me/.ros/camera_info/camera.yaml not found". The directory camera_info is missing itself, how can I make this file which this warning is asking?
